# validate this file:
#   curl --data-binary @.codecov.yml https://codecov.io/validate

comment: false

coverage:
  status:
    project:
      default:
        threshold: 1%
        if_not_found: success  # no commit found? still set a success
    patch:
      default:
        threshold: 1%
        if_not_found: success