# validate this file:
#   curl --data-binary @.codecov.yml https://codecov.io/validate

comment: false

coverage:
  status:
    # allow test coverage to drop by 1%, assume that it's typically due to CI problems
    patch:
      default:
        enabled: no
        if_not_found: success
    project:
      default:
        threshold: 1
        if_not_found: success  # no commit found? still set a success