version: "3.2"

services:
  devenv:
    image: septimaps/fikspunktsregister:ubuntu-18.04-devenv
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /fikspunktsregister
    working_dir: /fikspunktsregister
    environment:
      - ORACLE_PATH=/fikspunktsregister/misc/oracle
    depends_on:
      - oracledb
  oracledb:
    image: septimaps/oracle-12c-bootstrapped
    ports:
      - 1521:1521
