version: "3.2"

services:
  oraclelinux:
    image: oraclelinux:7
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /fikspunktsregister
    working_dir: /fikspunktsregister
    command: ./docker-compose.sh
    environment:
      - ORACLE_PATH=/fikspunktsregister/misc/oracle
    depends_on:
      - oracledb
  oracledb:
    image: septimaps/oracle-12c-bootstrapped
    ports:
      - 1521:1521
