name: fire-dev
channels:
  - conda-forge
  - msys2
dependencies:
  - black=22.6.*
  - click=8.1.*
  - cx_oracle=8.3.*
  - fiona=1.8.*
  - gama=2.*
  - graphviz=4.0.*
  - openpyxl=3.0.*
  - pandas=1.3.*
  - pip=22.1.*
  - pre-commit=2.15.*
  - pylint=2.14.*
  - pyproj=3.3.*
  - pytest-cov=3.0.*
  - pytest-freezegun=0.4.*
  - pytest-mock=3.8.*
  - pytest=7.1.*
  - python=3.9.*
  - sphinx-click=4.2.*
  - sphinx=5.0.*
  - sphinx_rtd_theme=1.0.*
  - sphinxcontrib-programoutput=0.16.*
  - sqlalchemy=1.4.*
  - xmltodict=0.13.*
