name: fire-dev
channels:
  - conda-forge
  - msys2
dependencies:
  - python=3.7
  - cx_oracle=7.0
  - sqlalchemy=1.2.13
  - pyproj
  - qgis=3.10
  - click
  - colorama
  - pandas=1.1.2
  - xlsxwriter
  - xlrd
  - xmltodict
  - gama
  - pytest
  - pytest-cov
  - pytest-mock
  - sphinx
  - sphinx_rtd_theme
  - sphinx-click
  - black
  - pylint
  - sqlalchemy_schemadisplay
  - fiona
  - m2-zip
  - pip
  - pip:
     - pb_tool
