CREATE TABLE BEREGNING (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   ID VARCHAR2(36) NOT NULL,
   REGISTRERINGFRA TIMESTAMP WITH TIME ZONE NOT NULL,
   REGISTRERINGTIL TIMESTAMP WITH TIME ZONE,
   MATERIALE VARCHAR2(100) NOT NULL,
   RAPPORTHTML VARCHAR2(100) NOT NULL,
   SAGSEVENTID VARCHAR2(100) NOT NULL
);

CREATE TABLE BEREGNING_KOORDINAT (

   BEREGNINGOBJECTID INTEGER NOT NULL,
   KOORDINATOBJECTID INTEGER NOT NULL,
   PRIMARY KEY (BEREGNINGOBJECTID, KOORDINATOBJECTID)
);

CREATE TABLE BEREGNING_PUNKT (

   BEREGNINGOBJECTID INTEGER NOT NULL,
   PUNKTOBJECTID INTEGER NOT NULL,
   PRIMARY KEY (BEREGNINGOBJECTID, PUNKTOBJECTID)
);

CREATE TABLE GEOMETRIOBJEKT (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   ID VARCHAR2(36) NOT NULL,
   REGISTRERINGFRA TIMESTAMP WITH TIME ZONE NOT NULL,
   REGISTRERINGTIL TIMESTAMP WITH TIME ZONE,
   GEOMETRI SDO_GEOMETRY NOT NULL,
   SAGSEVENTID VARCHAR2(100) NOT NULL,
   PUNKTID VARCHAR2(100) NOT NULL
);

CREATE TABLE KOORDINAT (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   ID VARCHAR2(36) NOT NULL,
   REGISTRERINGFRA TIMESTAMP WITH TIME ZONE NOT NULL,
   REGISTRERINGTIL TIMESTAMP WITH TIME ZONE,
   SRID VARCHAR2(10) NOT NULL,
   SX NUMBER,
   SY NUMBER,
   SZ NUMBER,
   T TIMESTAMP WITH TIME ZONE,
   TRANSFORMERET VARCHAR2(5) NOT NULL,
   X NUMBER,
   Y NUMBER,
   Z NUMBER,
   SAGSEVENTID VARCHAR2(100) NOT NULL,
   PUNKTID VARCHAR2(100) NOT NULL
);

CREATE TABLE OBSERVATION (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   ID VARCHAR2(36) NOT NULL,
   REGISTRERINGFRA TIMESTAMP WITH TIME ZONE NOT NULL,
   REGISTRERINGTIL TIMESTAMP WITH TIME ZONE,
   OBS1 NUMBER NOT NULL,
   OBS2 NUMBER,
   OBS3 NUMBER,
   OBS4 NUMBER,
   OBSERVATIONSTYPE VARCHAR2(100) NOT NULL,
   S1 NUMBER NOT NULL,
   S2 NUMBER,
   S3 NUMBER,
   S4 NUMBER,
   SAGSEVENTID VARCHAR2(100) NOT NULL,
   OPSTILLINGSPUNKTID VARCHAR2(100) NOT NULL,
   SIGTEPUNKT_1ID INTEGER,
   SIGTEPUNKT_2ID INTEGER
);

CREATE TABLE OBSERVATIONTYPE (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   BESKRIVELSE VARCHAR2(100) NOT NULL,
   NAMESPACE VARCHAR2(100) NOT NULL,
   OBS1 VARCHAR2(100),
   OBS2 VARCHAR2(100),
   OBS3 VARCHAR2(100),
   OBS4 VARCHAR2(100),
   OBSERVATIONSTYPE VARCHAR2(100) NOT NULL
);

CREATE TABLE PUNKT (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   ID VARCHAR2(36) NOT NULL,
   REGISTRERINGFRA TIMESTAMP WITH TIME ZONE NOT NULL,
   REGISTRERINGTIL TIMESTAMP WITH TIME ZONE,
   SAGSEVENTID VARCHAR2(100) NOT NULL
);

CREATE TABLE PUNKTINFO (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   ID VARCHAR2(36) NOT NULL,
   REGISTRERINGFRA TIMESTAMP WITH TIME ZONE NOT NULL,
   REGISTRERINGTIL TIMESTAMP WITH TIME ZONE,
   INFOTYPE VARCHAR2(100) NOT NULL,
   REELTAL NUMBER,
   TEKST VARCHAR2(100),
   SAGSEVENTID VARCHAR2(100) NOT NULL,
   PUNKTID VARCHAR2(100) NOT NULL
);

CREATE TABLE PUNKTINFOTYPE (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   ANVENDELSE VARCHAR2(100) NOT NULL,
   BESKRIVELSE VARCHAR2(100) NOT NULL,
   NAMESPACE VARCHAR2(100) NOT NULL,
   INFOTYPE VARCHAR2(100) NOT NULL
);

CREATE TABLE SAG (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   ID VARCHAR2(36) NOT NULL,
   JOURNALNUMMER VARCHAR2(100),
   SAGSTYPE VARCHAR2(21) NOT NULL,
   BEHANDLER VARCHAR2(100) NOT NULL,
   BESKRIVELSE VARCHAR2(100),
   REGISTRERINGFRA TIMESTAMP WITH TIME ZONE NOT NULL,
   REGISTRERINGTIL TIMESTAMP WITH TIME ZONE
);

CREATE TABLE SAGSHAENDELSE (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   HAENDELSE VARCHAR2(100) NOT NULL,
   ID VARCHAR2(36) NOT NULL,
   BESKRIVELSE VARCHAR2(100),
   REGISTRERINGFRA TIMESTAMP WITH TIME ZONE NOT NULL,
   REGISTRERINGTIL TIMESTAMP WITH TIME ZONE,
   SAGID VARCHAR2(100) NOT NULL
);

CREATE TABLE SRIDTYPE (

   OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
   BESKRIVELSE VARCHAR2(100) NOT NULL,
   NAMESPACE VARCHAR2(100) NOT NULL,
   SRID VARCHAR2(100) NOT NULL
);


ALTER TABLE KOORDINAT ADD CONSTRAINT CK_KOORDINAT_TRANSFORMER248 CHECK (TRANSFORMERET IN ('true', 'false'));
ALTER TABLE OBSERVATIONTYPE ADD CONSTRAINT CK_OBSERVATION_NAMESPACE087 CHECK (NAMESPACE IN ('obs'));
ALTER TABLE PUNKTINFOTYPE ADD CONSTRAINT CK_PUNKTINFOTY_ANVENDELSE138 CHECK (ANVENDELSE IN ('markering', 'reelTal', 'tekst'));
ALTER TABLE PUNKTINFOTYPE ADD CONSTRAINT CK_PUNKTINFOTY_NAMESPACE176 CHECK (NAMESPACE IN ('attr', 'net', 'ps'));
ALTER TABLE SAG ADD CONSTRAINT CK_SAG_SAGSTYPE050 CHECK (SAGSTYPE IN ('ændring af metadata', 'fejlrettelse', 'nymåling', 'udjævning'));
ALTER TABLE SRIDTYPE ADD CONSTRAINT CK_SRIDTYPE_NAMESPACE178 CHECK (NAMESPACE IN ('dk', 'epsg', 'fo', 'gl'));

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES ('GEOMETRIOBJEKT', 'GEOMETRI', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('Longitude', -180.0000, 180.0000, 0.005), MDSYS.SDO_DIM_ELEMENT('Latitude', -90.0000, 90.0000, 0.005)), 4326);

CREATE INDEX IDX_GEOMETRIOBJEKT_GEOMETRI ON GEOMETRIOBJEKT (GEOMETRI) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('layer_gtype=point');

COMMENT ON COLUMN BEREGNING.ID IS 'Persistent unik nøgle.';
COMMENT ON COLUMN BEREGNING.REGISTRERINGFRA IS 'Tidspunktet hvor registreringen er foretaget.';
COMMENT ON COLUMN BEREGNING.REGISTRERINGTIL IS 'Tidspunktet hvor en ny registrering er foretaget på objektet, og hvor denne version således ikke længere er den seneste.';
COMMENT ON COLUMN GEOMETRIOBJEKT.GEOMETRI IS 'Placeringskoordinat til brug for visning i f.eks et GIS sysstem.';
COMMENT ON COLUMN GEOMETRIOBJEKT.ID IS 'Persistent unik nøgle.';
COMMENT ON COLUMN GEOMETRIOBJEKT.REGISTRERINGFRA IS 'Tidspunktet hvor registreringen er foretaget.';
COMMENT ON COLUMN GEOMETRIOBJEKT.REGISTRERINGTIL IS 'Tidspunktet hvor en ny registrering er foretaget på objektet, og hvor denne version således ikke længere er den seneste.';
COMMENT ON COLUMN KOORDINAT.ID IS 'Persistent unik nøgle.';
COMMENT ON COLUMN KOORDINAT.REGISTRERINGFRA IS 'Tidspunktet hvor registreringen er foretaget.';
COMMENT ON COLUMN KOORDINAT.REGISTRERINGTIL IS 'Tidspunktet hvor en ny registrering er foretaget på objektet, og hvor denne version således ikke længere er den seneste.';
COMMENT ON COLUMN KOORDINAT.SRID IS 'Unik værdi til angivelse af et koordinatsystem.';
COMMENT ON COLUMN KOORDINAT.SX IS 'Spredning af x.';
COMMENT ON COLUMN KOORDINAT.SY IS 'Spredning af y.';
COMMENT ON COLUMN KOORDINAT.SZ IS 'Spredning af z.';
COMMENT ON COLUMN KOORDINAT.T IS 'Observationstidspunktet.';
COMMENT ON COLUMN KOORDINAT.TRANSFORMERET IS 'Angivelse om positionen er målt, eller transformeret fra et andet koordinatsystem';
COMMENT ON COLUMN KOORDINAT.X IS 'x koordinat.';
COMMENT ON COLUMN KOORDINAT.Y IS 'y koordinat.';
COMMENT ON COLUMN KOORDINAT.Z IS 'z koordinat.';
COMMENT ON COLUMN OBSERVATION.ID IS 'Persistent unik nøgle.';
COMMENT ON COLUMN OBSERVATION.REGISTRERINGFRA IS 'Tidspunktet hvor registreringen er foretaget.';
COMMENT ON COLUMN OBSERVATION.REGISTRERINGTIL IS 'Tidspunktet hvor en ny registrering er foretaget på objektet, og hvor denne version således ikke længere er den seneste.';
COMMENT ON COLUMN PUNKT.ID IS 'Persistent unik nøgle.';
COMMENT ON COLUMN PUNKT.REGISTRERINGFRA IS 'Tidspunktet hvor registreringen er foretaget.';
COMMENT ON COLUMN PUNKT.REGISTRERINGTIL IS 'Tidspunktet hvor en ny registrering er foretaget på objektet, og hvor denne version således ikke længere er den seneste.';
COMMENT ON COLUMN PUNKTINFO.ID IS 'Persistent unik nøgle.';
COMMENT ON COLUMN PUNKTINFO.REGISTRERINGFRA IS 'Tidspunktet hvor registreringen er foretaget.';
COMMENT ON COLUMN PUNKTINFO.REGISTRERINGTIL IS 'Tidspunktet hvor en ny registrering er foretaget på objektet, og hvor denne version således ikke længere er den seneste.';
COMMENT ON COLUMN SAG.BEHANDLER IS 'Angivelse af en sagsbehandler.';
COMMENT ON COLUMN SAG.BESKRIVELSE IS 'Kort beskrivelse af en fikspunktssag.';
COMMENT ON COLUMN SAG.ID IS 'Persistent unik nøgle.';
COMMENT ON COLUMN SAG.REGISTRERINGFRA IS 'Tidspunktet hvor registreringen er foretaget.';
COMMENT ON COLUMN SAG.REGISTRERINGTIL IS 'Tidspunktet hvor en ny registrering er foretaget på objektet, og hvor denne version således ikke længere er den seneste.';
COMMENT ON COLUMN SAG.SAGSTYPE IS 'Inddeling af fikspunktsager ud fra opgavetype.';
COMMENT ON COLUMN SAGSHAENDELSE.BESKRIVELSE IS 'Kort beskrivelse af en fikspunktssag.';
COMMENT ON COLUMN SAGSHAENDELSE.ID IS 'Persistent unik nøgle.';
COMMENT ON COLUMN SAGSHAENDELSE.REGISTRERINGFRA IS 'Tidspunktet hvor registreringen er foretaget.';
COMMENT ON COLUMN SAGSHAENDELSE.REGISTRERINGTIL IS 'Tidspunktet hvor en ny registrering er foretaget på objektet, og hvor denne version således ikke længere er den seneste.';
